import type { SidebarsConfig } from '@docusaurus/plugin-content-docs';

// 自动从 docs/ 目录结构生成侧边栏
// Docusaurus 会按文件夹+文件名前缀数字排序，自动剥离 `01-` `02-` 这类前缀
const sidebars: SidebarsConfig = {
  tutorialSidebar: [
    {
      type: 'autogenerated',
      dirName: '.',
    },
  ],
};

export default sidebars;
